# Generated by Django 5.2 on 2025-05-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название настроения')),
            ],
            options={
                'db_table': 'moods',
            },
        ),
        migrations.CreateModel(
            name='GameGenreMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('rating_year', models.FloatField(verbose_name='Рейтинг за год')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_ml_data', to='games.game', verbose_name='Игра')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.genre', verbose_name='Жанр')),
            ],
            options={
                'db_table': 'game_genre_ml_data',
                'unique_together': {('game', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='GamePlatformMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_ml_data', to='games.game', verbose_name='Игра')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.platform', verbose_name='Платформа')),
            ],
            options={
                'db_table': 'game_platform_ml_data',
                'unique_together': {('game', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='GameSubgenreMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgenre', models.CharField(max_length=100, verbose_name='Поджанр')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('rating_year', models.FloatField(verbose_name='Рейтинг за год')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenre_ml_data', to='games.game', verbose_name='Игра')),
            ],
            options={
                'db_table': 'game_subgenre_ml_data',
                'unique_together': {('game', 'subgenre')},
            },
        ),
        migrations.CreateModel(
            name='GameMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='games.game', verbose_name='Игра')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mldata.mood', verbose_name='Настроение')),
            ],
            options={
                'db_table': 'game_moods',
                'unique_together': {('game', 'mood')},
            },
        ),
    ]
