# Generated by Django 5.2 on 2025-05-12 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_name', models.CharField(max_length=255, verbose_name='Название источника цены')),
                ('buy_link', models.URLField(verbose_name='Ссылка для покупки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='games.game', verbose_name='Игра')),
            ],
            options={
                'db_table': 'origin_prices',
            },
        ),
    ]
