# Generated by Django 5.2 on 2025-05-14 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='games.game', verbose_name='Игра')),
            ],
            options={
                'db_table': 'pricing',
            },
        ),
    ]
