# Generated by Django 5.2 on 2025-05-21 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='system_requirements',
        ),
        migrations.AddField(
            model_name='game',
            name='system_requirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.systemrequirement', verbose_name='Системные требования'),
        ),
    ]
