# Generated by Django 5.2 on 2025-05-21 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_rename_system_requirement_game_system_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='system_requirements',
        ),
        migrations.AddField(
            model_name='game',
            name='system_requirement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.systemrequirement', verbose_name='Системные требования'),
        ),
    ]
