# Generated by Django 5.2 on 2025-05-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('cover_image', 'Обложка'), ('background_video', 'Фоновое видео'), ('screenshot', 'Скриншот'), ('trailer', 'Трейлер'), ('other_video', 'Другое видео')], max_length=20, verbose_name='Тип медиа')),
                ('url', models.URLField(verbose_name='URL медиа')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='games.game', verbose_name='Игра')),
            ],
            options={
                'db_table': 'media_links',
            },
        ),
    ]
